Updated compile script.

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,40 +1,34 @@
 #!/bin/bash
 
-# CHAPTERS=chap1,chap2,biblio
-CHAPTERS=all
+function check_status {
+  if [ $? -eq 0 ]; then
+    echo -e "[  \033[32mOK\033[0m  ]"
+  else
+    echo -e "[\033[31mFAILED\033[0m]"
+    exit 1
+  fi
+}
 
 echo -e -n " Running LaTeX 1............ "
-echo $CHAPTERS | latex main.tex > /dev/null
-if [ $? -eq 0 ]; then
-  echo -e "[  \033[32mOK\033[0m  ]"
-fi
+latex main.tex > /dev/null
+check_status
 
 echo -e -n " Running BibTeX............. "
 bibtex main.aux > /dev/null
-if [ $? -eq 0 ]; then
-  echo -e "[  \033[32mOK\033[0m  ]"
-fi
+check_status
 
 echo -e -n " Running LaTeX 2............ "
-echo $CHAPTERS | latex main.tex > /dev/null
-if [ $? -eq 0 ]; then
-  echo -e "[  \033[32mOK\033[0m  ]"
-fi
+latex main.tex > /dev/null
+check_status
 
 echo -e -n " Running LaTeX 3............ "
-echo $CHAPTERS | latex main.tex > /dev/null
-if [ $? -eq 0 ]; then
-  echo -e "[  \033[32mOK\033[0m  ]"
-fi
+latex main.tex > /dev/null
+check_status
 
 echo -e -n " Running dvips.............. "
 dvips -Ppdf main.dvi > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-  echo -e "[  \033[32mOK\033[0m  ]"
-fi
+check_status
 
 echo -e -n " Running ps2pdf............. "
 ps2pdf main.ps main.pdf > /dev/null
-if [ $? -eq 0 ]; then
-  echo -e "[  \033[32mOK\033[0m  ]"
-fi
+check_status
